# GitLab CI/CD 配置檔案
# 適用於 Vue.js 專案的完整 CI/CD 流程

stages:
  - install
  - test
  - build
  - deploy

# 快取 node_modules 以加速建置
cache:
  paths:
    - node_modules/
    - .npm/

# 安裝依賴
install_dependencies:
  stage: install
  image: node:22.19.0
  script:
    - npm ci
    - npm run prepare
  artifacts:
    paths:
      - node_modules/
    expire_in: 1 hour

# 執行單元測試和整合測試
test_unit:
  stage: test
  image: node:22.19.0
  dependencies:
    - install_dependencies
  script:
    - npm run test:unit:coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week

# 執行 E2E 測試
test_e2e:
  stage: test
  image: node:22.19.0
  dependencies:
    - install_dependencies
  before_script:
    - npx playwright install --with-deps
  script:
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - test-results/
    expire_in: 1 week

# 建置專案
build:
  stage: build
  image: node:22.19.0
  dependencies:
    - install_dependencies
  script:
    - export NODE_ENV=production
    - echo "開始建置 production 版本"
    - rm -rf dist/
    - npm run build-with-type-check
    - echo "建置完成，檢查結果"
    - ls -la dist/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

# 部署到 GitHub Pages (需要設定 GITHUB_TOKEN)
deploy_github_pages:
  stage: deploy
  image: node:22.19.0
  dependencies:
    - build
  script:
    - npm install -g gh-pages
    - gh-pages -d dist -t true
  only:
    - main
    - master
  when: manual  # 手動觸發部署

# 部署到 GitLab Pages (自動部署)
pages:
  stage: deploy
  image: node:22.19.0
  dependencies:
    - build
  script:
    - export NODE_ENV=production
    - echo "開始部署到 GitLab Pages"
    - echo "檢查 dist 目錄"
    - ls -la dist/
    - echo "建立 public 目錄"
    - mkdir -p public
    - echo "複製檔案到 public 目錄"
    - cp -r dist/* public/
    - echo "檢查 public 目錄內容"
    - ls -la public/
    - echo "檢查 index.html 是否存在"
    - test -f public/index.html && echo "index.html 存在" || echo "index.html 不存在"
    - echo "檢查 public 目錄結構"
    - find public/ -type f | head -10
  artifacts:
    paths:
      - public
    expire_in: 1 hour
  only:
    - main
    - master

